import assert from 'node:assert/strict';
import test, {before,afterEach} from 'node:test';
import {Window} from 'happy-dom';
import * as React from 'react';
import type {Root} from 'react-dom/client';
const {act}=React;const browser=new Window({url:'https://mm-llm.local/'});browser.document.write('<!doctype html><html><body></body></html>');
for(const [name,value] of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,Node:browser.Node,Element:browser.Element,HTMLElement:browser.HTMLElement,HTMLButtonElement:browser.HTMLButtonElement,Event:browser.Event,KeyboardEvent:browser.KeyboardEvent,MouseEvent:browser.MouseEvent,MutationObserver:browser.MutationObserver,ResizeObserver:browser.ResizeObserver,IntersectionObserver:browser.IntersectionObserver,getComputedStyle:browser.getComputedStyle}))Object.defineProperty(globalThis,name,{value,writable:true,configurable:true});
Object.defineProperty(globalThis,'IS_REACT_ACT_ENVIRONMENT',{value:true,configurable:true});globalThis.requestAnimationFrame=(cb)=>setTimeout(()=>cb(Date.now()),0) as any;globalThis.cancelAnimationFrame=id=>clearTimeout(id);browser.requestAnimationFrame=globalThis.requestAnimationFrame;browser.cancelAnimationFrame=globalThis.cancelAnimationFrame;
let createRoot:typeof import('react-dom/client')['createRoot'],VoicePanel:typeof import('../src/renderer/src/VoicePanel')['VoicePanel'],App:typeof import('../src/renderer/src/App')['default'],ConfirmProvider:typeof import('../src/renderer/src/components/ConfirmDialog')['ConfirmProvider'];
let root:Root|null=null,host:HTMLDivElement|null=null;
class Track extends browser.EventTarget{enabled=true;stops=0;stop(){this.stops++}}
class AudioNode{disconnects=0;connect(){}disconnect(){this.disconnects++}}
class Context{static all:Context[]=[];sampleRate=48000;currentTime=0;destination={};closed=0;buffers:any[]=[];audioWorklet={addModule:async(url:string)=>{assert.match(url,/voice-capture\.js$/)}};constructor(){Context.all.push(this)}createMediaStreamSource(){return new AudioNode()}createGain(){return Object.assign(new AudioNode(),{gain:{value:1}})}async resume(){}async close(){this.closed++}createBuffer(_c:number,n:number){return{getChannelData:()=>new Float32Array(n)}}createBufferSource(){const s=Object.assign(new AudioNode(),{buffer:null,onended:null,stop(){this.stopped=true},start(){},stopped:false});this.buffers.push(s);return s}}
class Worklet extends AudioNode{static all:Worklet[]=[];port={onmessage:null as any,postMessage(){},closed:false,close(){this.closed=true}};constructor(){super();Worklet.all.push(this)}}
const now='2026-10-08T00:00:00Z';const thread={id:'voice-thread',title:'Synthetic',modelId:'gpt-6-astra',createdAt:now,updatedAt:now,webSearchMode:'off' as const,reasoningMode:'auto' as const,instruction:'',advanced:{},attachmentConsent:false,messages:[],messageCount:0};
const models=[{id:'gpt-6-astra',type:'llm' as const},{id:'gpt-realtime-2.1-mini',type:'realtime' as const},{id:'gemini-3.8-live',type:'realtime' as const},{id:'gpt-unknown',type:'realtime' as const},{id:'stt-rt-v5',type:'audio' as const}];
before(async()=>{({createRoot}=await import('react-dom/client'));({VoicePanel}=await import('../src/renderer/src/VoicePanel'));({default:App}=await import('../src/renderer/src/App'));({ConfirmProvider}=await import('../src/renderer/src/components/ConfirmDialog'));});
async function render(ui:React.ReactNode){if(!host){host=document.createElement('div');document.body.append(host);root=createRoot(host)}await act(async()=>root!.render(ui));await flush()}
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,10))})}
async function click(e:Element){await act(async()=>{(e as HTMLElement).focus();(e as HTMLElement).click()});await flush()}
async function select(e:HTMLSelectElement,value:string){await act(async()=>{e.value=value;e.dispatchEvent(new browser.Event('change',{bubbles:true}))});await flush()}
const button=(s:string)=>[...document.querySelectorAll<HTMLButtonElement>('.voice-panel button')].find(b=>b.textContent===s)!;
function fixture(options:{pending?:boolean;denied?:boolean}={}){Context.all=[];Worklet.all=[];const track=new Track();let resolve:()=>void=()=>{};let listener:(e:any)=>void=()=>{};const counts={mic:0,prepare:0,connect:0,stop:0,sub:0,frames:0,save:0,apply:0,control:0,streams:0,logout:0};let id='';let applied='';const stream={getTracks:()=>[track],getAudioTracks:()=>[track]};
 Object.defineProperty(browser.navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async(request:any)=>{assert.equal(request.video,false);counts.mic++;if(options.denied)throw new Error('synthetic permission denied');if(options.pending)return new Promise(r=>resolve=()=>r(stream));return stream}}});
 Object.defineProperty(globalThis,'AudioContext',{configurable:true,value:Context});Object.defineProperty(globalThis,'AudioWorkletNode',{configurable:true,value:Worklet});
 const emit=(e:any)=>listener({id,...e});const api={prepareVoice:async(r:any)=>{counts.prepare++;id=r.id;emit({type:'state',state:'requesting_permission'})},connectVoice:async()=>{counts.connect++;emit({type:'state',state:'active'})},stopVoice:async(_id:string,immediate:boolean)=>{counts.stop++;if(immediate||!options.pending)emit({type:'state',state:'closed'})},sendVoiceFrame:async()=>{counts.frames++},controlVoice:async()=>{counts.control++},onVoiceEvent:(cb:any)=>{listener=cb;counts.sub++;return()=>{counts.sub--}},saveVoiceText:async()=>{counts.save++;return {...thread}},
  getSession:async()=>({authenticated:true,models,credits:{total:{remaining:1000}}}),getSettings:async()=>({theme:'light',fontSize:'medium',defaultInstruction:''}),setThemePreference:async()=>{},listThreads:async()=>[thread],loadThread:async()=>thread,listProjects:async()=>[],listBackgroundResponses:async()=>[],getUpdateState:async()=>({status:'idle',currentVersion:'0.5.1'}),onUpdateChanged:()=>()=>{},discardAttachments:async()=>{},getCredits:async()=>({total:{remaining:1000}}),streamChat:()=>{counts.streams++;return()=>{}},logout:async()=>{counts.logout++;emit({type:'state',state:'closed'})},cancelLogin:async()=>false};Object.assign(browser,{mmllm:api});
 return {track,counts,resolve:()=>resolve(),emit,api,onApply:(text:string)=>{counts.apply++;applied=text},applied:()=>applied};}
async function panel(f:ReturnType<typeof fixture>){await render(<VoicePanel models={models} threadId={thread.id} canApply onApply={f.onApply} onSaved={()=>{}} onUsageChanged={()=>{}}/>);await act(async()=>{document.querySelector('details')!.open=true});await flush()}
async function start(){await click(document.querySelector('[aria-label="음성 외부 전송과 과금 동의"]')!);await click(button('시작'))}
afterEach(async()=>{if(root)await act(async()=>root!.unmount());root=null;host?.remove();host=null;});
test('actual VoicePanel dedicated catalog/consent and mode changes make no network; double Start uses one request and mic with accessible status',async()=>{
 const f=fixture();await panel(f);assert.equal(button('시작').disabled,true);const picker=document.querySelector<HTMLSelectElement>('[aria-label="실시간 음성 모델"]')!;assert.deepEqual([...picker.options].map(o=>o.value),['gpt-realtime-2.1-mini','gemini-3.8-live']);await select(picker,'gemini-3.8-live');assert.equal(f.counts.prepare,0);await click(document.querySelector('[aria-label="음성 외부 전송과 과금 동의"]')!);await act(async()=>{button('시작').click();button('시작').click()});await flush();assert.equal(f.counts.prepare,1);assert.equal(f.counts.connect,1);assert.equal(f.counts.mic,1);assert.match(document.querySelector('.voice-actions [role="status"]')!.textContent!,/마이크 사용 중.*마이크 켜짐/);assert.match(document.body.textContent!,/1분.*예약.*실제 사용량.*음소거는 과금 종료가 아닙니다/);await click(button('음소거'));assert.equal(f.track.enabled,false);assert.equal(button('마이크 다시 켜기').getAttribute('aria-pressed'),'true');await click(button('종료'));assert.equal(f.track.stops,1);assert.equal(Context.all[0].closed,1);assert.equal(Worklet.all[0].port.onmessage,null);assert.equal(f.counts.sub,0);
});
test('actual VoicePanel permission denial performs no mint/audio, and cancel/unmount before delayed getUserMedia immediately releases late track',async()=>{
 const denied=fixture({denied:true});await panel(denied);await start();assert.equal(denied.counts.connect,0);assert.equal(denied.counts.frames,0);assert.equal(denied.counts.sub,0);assert.match(document.querySelector('[role="alert"]')!.textContent!,/권한.*거부/);
 await render(<></>);const f=fixture({pending:true});await panel(f);await start();assert.equal(f.counts.mic,1);await click(button('종료'));await act(async()=>{f.emit({type:'state',state:'closed'});f.resolve()});await flush();assert.equal(f.counts.connect,0);assert.equal(f.track.stops,1);assert.equal(Context.all.length,0);assert.equal(f.counts.sub,0);
 await render(<></>);const g=fixture({pending:true});await panel(g);await start();await render(<></>);await act(async()=>g.resolve());await flush();assert.equal(g.track.stops,1);assert.equal(g.counts.connect,0);assert.equal(g.counts.sub,0);
});
test('actual voice interruption stops scheduled playback, track ended and view collapse clean mic/context/listener',async()=>{
 const f=fixture();await panel(f);await start();await act(async()=>f.emit({type:'audio',sequence:1,sampleRate:24000,bytes:new Uint8Array(4800),itemId:'item'}));Context.all[0].currentTime=.04;await act(async()=>f.emit({type:'interrupt',interruption:1,itemId:'item'}));assert.equal(Context.all[0].buffers[0].stopped,true);assert.equal(f.counts.control,1);await act(async()=>f.track.dispatchEvent(new Event('ended')));assert.equal(f.track.stops,1);assert.equal(Context.all[0].closed,1);assert.equal(f.counts.sub,0);assert.match(document.querySelector('[role="alert"]')!.textContent!,/장치.*다시 시작/);
 await render(<></>);const g=fixture();await panel(g);await start();await act(async()=>{document.querySelector('details')!.open=false});await flush();assert.equal(g.track.stops,1);assert.equal(Context.all[0].closed,1);assert.equal(g.counts.sub,0);
});
test('actual dictation finite preview needs closed final and explicit apply; conversation text save opt-in defaults off',async()=>{
 const f=fixture();await panel(f);await select(document.querySelector('[aria-label="음성 용도"]')!,'dictation');assert.equal(f.counts.prepare,0);assert.match(document.body.textContent!,/Sonioxには|Soniox에는 필터가 없습니다/);await start();await act(async()=>f.emit({type:'text',final:'synthetic final',provisional:'temporary'}));assert.equal(button('확정문을 초안에 추가').disabled,true);await click(button('종료'));await click(button('확정문을 초안에 추가'));assert.equal(f.counts.apply,1);assert.equal(f.applied(),'synthetic final');assert.equal(f.counts.streams,0);assert.equal(f.counts.save,0);
 await render(<></>);const g=fixture();await panel(g);await start();await act(async()=>g.emit({type:'text',final:'voice text',provisional:''}));await click(button('종료'));assert.equal(button('텍스트 저장').disabled,true);assert.equal(g.counts.save,0);await click(document.querySelector('[aria-label="음성 텍스트 암호화 저장 동의"]')!);await click(button('텍스트 저장'));assert.equal(g.counts.save,1);
});
test('actual App applies dictation final after existing composer draft without autosend and logout unmounts all audio',async()=>{
 const f=fixture();await render(<ConfirmProvider><App/></ConfirmProvider>);await act(async()=>{document.querySelector<HTMLDetailsElement>('.voice-panel')!.open=true});await flush();const input=document.querySelector<HTMLTextAreaElement>('.composer-input')!;
 await act(async()=>{Object.getOwnPropertyDescriptor(browser.HTMLTextAreaElement.prototype,'value')!.set!.call(input,'existing draft');input.dispatchEvent(new browser.Event('input',{bubbles:true}))});await select(document.querySelector('[aria-label="음성 용도"]')!,'dictation');await start();await act(async()=>f.emit({type:'text',final:'accepted dictation',provisional:'not final'}));await click(button('종료'));await click(button('확정문을 초안에 추가'));assert.equal(document.querySelector<HTMLTextAreaElement>('.composer-input')!.value,'existing draft\n\naccepted dictation');assert.equal(f.counts.streams,0);
 await click(button('시작'));assert.equal(f.counts.connect,2);await click(document.querySelector('.account-trigger')!);await click(document.querySelector('.logout-action')!);assert.equal(f.counts.logout,1);assert.equal(f.counts.sub,0);assert.equal(f.track.stops,2);assert.equal(Context.all.every(c=>c.closed===1),true);assert.equal(document.querySelector('.voice-panel'),null);
});
test('actual panel keyboard focus, narrow portrait and both themes retain native controls and session cleanup on unmount',async()=>{
 for(const theme of ['light','dark']){const f=fixture();document.documentElement.dataset.theme=theme;browser.innerWidth=680;browser.innerHeight=820;await panel(f);const summary=document.querySelector('summary')!;(summary as HTMLElement).focus();assert.equal(document.activeElement,summary);await start();button('음소거').focus();assert.equal(document.activeElement,button('음소거'));assert.equal(document.querySelectorAll('.voice-panel select').length,2);assert.equal(document.querySelector('[aria-label="음성 외부 전송과 과금 동의"]')!.tagName,'INPUT');await render(<></>);assert.equal(f.track.stops,1);assert.equal(Context.all[0].closed,1);assert.equal(f.counts.sub,0);}
});
